apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      service: worker
  template:
    metadata:
      labels:
        app: worker
        service: worker
    spec:
      containers:
        - name: worker
          image: robopizzaregistry.azurecr.io/worker:v1
          imagePullPolicy: Always